version: "3.8"

services:
  localstack:
    container_name: "localstack-pro"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # External services port range
      - "127.0.0.1:5432:5432"            # Standard PostgreSQL port mapping for RDS
    environment:
      - DEBUG=1
      # The LOCALSTACK_AUTH_TOKEN is required for Pro features. 
      # Pass it in your terminal before running docker-compose, e.g.
      # $env:LOCALSTACK_AUTH_TOKEN="your_token_here"; docker-compose up -d
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack-volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack/init:/etc/localstack/init"

  app:
    build: .
    container_name: "pati-app"
    ports:
      - "8080:8080"
    environment:
      # These environment variables will be injected into application.properties
      - DB_URL=jdbc:postgresql://localstack:5432/patidb
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - localstack
