apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pati-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # This rewrite-target handles removing /api before it hits your Spring Boot app
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: pati-backend-service
            port:
              number: 80
